python3 1.repo_cleanup.py
python3 2.entry_processing.py
python3 3.get_prediciton_data.py
python3 gk_training.py
python3 def_training.py
python3 mid_training.py
python3 fwd_training.py
python3 Predictions.py
python3 predictionsToDatabase.py